### ISSUE TITLE
Things to handle

### ISSUE THREAD

**Issue by sudarshansudarshan** [sudarshansudarshan/peerevaluation#2]
1. Buy the server space as suggested in the quotation. Please use my fotografik funding @ak-1983 do this asap.
2. The following is what I would expect:

The teacher uploads email ids, which is a csv file.
As a second step, the teacher uploads pdf files in one batch. 
Then the students get an email alert with their user id (email by default) and a password (this should expire in a stipulated time).
k value should be specified by the teacher. 
Based on the k value, we will be sending each answer script to k students uniformly at random. 
The student evaluates and submits his evaluation and then logs out. 
The student will be able to turn in and then un turn in too before the stipulated time. This should work exactly like the google classroom.

**Comment by imrohitvk** [comment]
The stipulated time functionality for the student to resubmit the evaluation will be added in the next version. All other changes like password expiring(reset on the first login) and based on the k value the files will be distributed to the students.
